### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by tfheen** [tftp-go-team/libgotftp#2]
libgotftp seems to be missing a license. Could you please add one?

**Comment by rmedaer** [comment]
It should be a LGPL v3 I guess.. Let see with @epeli and @sspans !

**Comment by esamattis** [comment]
MIT

**Comment by cavus700** [comment]
Maybe a little bit late but I would like to chime in here. It would be great to have a license here :D

**Comment by brmzkw** [comment]
Just added a wtfpl license. BTW the directory layout of this repository is a bit outdated, if anyone wants to update it to follow https://github.com/tftp-go-team/hooktftp I am willing to review PRs!
